- set_fact:
    cli_reg_pol_match: "{{ found_configuration_rules | json_query(query) | first | default({}) }}"
  vars:
    query: '[? (field == `{{ current_configuration_rules.field }}` && type == `{{ current_configuration_rules.type }}`) ]'

- set_fact:
    configuration_rules_isfound: "{{ lookup('dict', configuration_rules_match) | length > 0 }}"

- name: "Delete  group configuration rule {{ current_configuration_rules.field }} and {{ current_configuration_rules.type }} of realm {{ item.name }}"
  uri:
    url: "{{ keycloak_proxy_host }}/admin/realms/{{ item.name }}/agm/admin/configuration-rules/{{ configuration_rules_match.id }}"
    method: "DELETE"
    headers:
      Authorization: "Bearer {{ tokens.json.access_token }}"
    status_code: "204"
  when: configuration_rules_isfound