---
- name: Install dependencies
  apt:
    pkg:
      - curl
      - git
      - nginx

- name: Add node repository
  shell: curl -sL https://deb.nodesource.com/setup_14.x | sudo bash -
  args:
    warn: no

- name: Install node and npm
  apt:
    pkg:
      - build-essential
      - nodejs
      - npm

- name: Install pm2
  npm:
    name: pm2
    global: yes
